name          'tobru-knot'
version       '0.1.0'
source        'https://github.com/tobru/puppet-knot'
author        'tobru'
license       'BSD-3-Clause'
summary       'Manage and configure Knot DNS'
description   ''
project_page  'https://github.com/tobru/puppet-knot'

dependency 'puppetlabs/stdlib'
